{% set name = "amazon-braket-ocean-plugin" %}
{% set version = "1.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-ocean-plugin-{{ version }}.tar.gz
  sha256: 5fa3cb1588c42696abe8ce08b0a56dbdba92da8ac391b76d59bc52a28ff6b7dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - amazon-braket-sdk >=1.25.0
    - boltons >=20.0.0
    - boto3 >=1.18.13
    - colorama >=0.4.3
    - dimod >=0.8.13
    - dwave-cloud-client >=0.9.4
    - jsonref
    - python >={{ python_min }}
    - wheel >=0.36.2

test:
  imports:
    - braket
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/amazon-braket-ocean-plugin-python
  summary: An open source framework for interacting with D-Wave's Ocean library through Amazon Braket
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
